first web slider-supercollider communication established
via websocket
slider only displayed after code is changed, otherwise throws error:
DOMException: An attempt was made to use an object that is not, or is no longer, usable